### ISSUE TITLE
Graphs are displayed on the page before merging?

### ISSUE THREAD

**Issue by TanskaAnnna** [SuLab/DrugMechDB#263]
I have recently been reviewing pull requests and asked for corrections before merging. It turned out that despite of the fact that I did not merge those pull request, the graphs from those pull requests are displayed on the page. For pull requests that needed corrections and were closed by a curator I can still see the paths from those closed pull requests. The page displays all the graphs for an each corrected pull request, for the same group. Therefore if there were 2 corrections for the same pull request I can now see 2 paths for an each drug in a group, including the ones with errors. Please let me know if you need more details for this issue.

**Comment by andrewsu** [comment]
@TanskaAnnna if you have specific examples/IDs/links, can you post them please?

**Comment by dede2021** [comment]
Please note that when submitting these new requests we may need to do so including the `id` that made its way into the website. I.e. it would be as [updating existing paths](https://github.com/SuLab/DrugMechDB/blob/main/SubmissionGuide.md#updating-an-existing-path), I'd have thought.

**Comment by TanskaAnnna** [comment]
@andrewsu here are some examples:
1)From curated batch_86 #255 which has not been merged by me and it is currently waiting for some corrections: there is a path for Mucopolysaccharidosis-laronidase, displayed on the page, here is the link: https://sulab.github.io/DrugMechDB/db00090-mesh-d008059-1.html another drug form the same batch: https://sulab.github.io/DrugMechDB/db00137-mesh-d000080343-1.html. Looks like all of them are displayed on the page.
2) Another example is with pull requests that were submitted multimple times, due to corrections.  Group_85 has 2 closed pull requests and one open and looks like all graphs (I checked that randomly) from that group are displayed 3 times. Here is an example for Trichlormethiazide-Hypertension:
a) https://sulab.github.io/DrugMechDB/db01021-mesh-d006973-1.html
b) https://sulab.github.io/DrugMechDB/db01021-mesh-d006973-2.html
c) https://sulab.github.io/DrugMechDB/db01021-mesh-d006973-3.html

Is it possible that the Validate PR Action maybe responsible for this weird behaviour?

**Comment by TanskaAnnna** [comment]
@dede2021 I think you might be right that when it comes to re-submitting pull requests we may need to do that with the `id` for each path.

**Comment by umasrisankarlal** [comment]
I too came across the same issue, which I have explained in the Slack portal. 
The whole batch that needs correction can be done by deleting all existing path id's and then submit as a fresh one (as suggested by Anna, which is a much easier way to avoid duplicates). When there are few drug-disease combinations, that needs to be created, using the path id, corrected path can be resubmitted.

**Comment by TanskaAnnna** [comment]
This issue has been resolved.
