### ISSUE TITLE
Yaml file to output graph test

### ISSUE THREAD

**Issue by TanskaAnnna** [SuLab/DrugMechDB#9]
Hi @mmayers12.  What's the simples way to run DrugMechDB yaml input to see the graph (output)?  I think this would be helpful for my curation to check for any manual errors.

**Comment by mmayers12** [comment]
Visualization can be performed with [Google CoLab Notebook](https://colab.research.google.com/github/SuLab/DrugMechDB/blob/master/path_visualization.ipynb)
